log_level: "debug"

default_port: 11433
default_rate_limit: "1000 per hour"
rate_limit: "100 per minute"

llm_providers:
  openai:
    base_url: "https://api.openai.com"
    headers:
      Content-Type: "application/json"

  groq:
    base_url: "https://api.groq.com/openai"
    headers:
      Content-Type: "application/json"

  ollama:
    base_url: "http://localhost:11434"
    headers:
      Content-Type: "application/json"

  cerebras:
    base_url: "https://api.cerebras.ai"
    headers:
      Content-Type: "application/json"

  deepseek:
    base_url: "https://api.deepseek.com"
    headers:
      Content-Type: "application/json"

  openrouter:
    base_url: "https://openrouter.ai/api"
    headers:
      Content-Type: "application/json"
